name: PostgreSQL Builds
on:
  workflow_dispatch:
    inputs:
      maven-cache-key:
        type: string
        description: "The cache key to use to restore/save build caches."
        default: ''
      max-parallel:
        type: number
        description: "The maximum number of workers to consume, by default uses all available."
        default: ''
jobs:
  build-posgresql:
    strategy:
      max-parallel: ${{ inputs.max-parallel }}
      fail-fast: false
      matrix:
        profile: ["assembly,postgres-14", "assembly,postgres-18,pgoutput-decoder"]
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    name: PostgreSQL - ${{ matrix.profile }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build PostgreSQL - ${{ matrix.profile }}
        uses: ./.github/actions/build-debezium-postgres
        with:
          maven-cache-key: ${{ inputs.maven-cache-key }}-${{ hashFiles('**/pom.xml') }}
          profile: ${{ matrix.profile }}
