name: MySQL Builds
on:
  workflow_dispatch:
    inputs:
      maven-cache-key:
        type: string
        description: "The cache key to use to restore/save build caches."
        default: ''
      max-parallel:
        type: number
        description: "The maximum number of workers to consume, by default uses all available."
        default: ''
jobs:
  build-mysql:
    strategy:
      max-parallel: ${{ inputs.max-parallel }}
      fail-fast: false
      matrix:
        profile: ["mysql-ci", "mysql-ci-gtids", "mysql-ci-percona", "mysql-ci-ssl"]
        version-mysql-server: ["8.0", "8.4", "9.7"]
        # Always exclude mysql-ci-gtids and mysql-ci-ssl profiles for all versions except most recent
        exclude:
          - profile: "mysql-ci-gtids"
            version-mysql-server: "8.0"
          - profile: "mysql-ci-gtids"
            version-mysql-server: "8.4"
          - profile: "mysql-ci-ssl"
            version-mysql-server: "8.0"
          - profile: "mysql-ci-ssl"
            version-mysql-server: "8.4"
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    name: MySQL ${{ matrix.version-mysql-server }} - ${{ matrix.profile }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build MySQL ${{ matrix.version-mysql-server }} - ${{ matrix.profile }}
        uses: ./.github/actions/build-debezium-mysql
        with:
          maven-cache-key: ${{ inputs.maven-cache-key }}-${{ hashFiles('**/pom.xml') }}
          version-mysql-server: ${{ matrix.version-mysql-server }}
          profile: ${{ matrix.profile }}
